### ISSUE TITLE
最近也在写蘑菇丁打卡

### ISSUE THREAD

**Issue by SuzukiHonoka** [NothAmor/MoGuDing-Web#2]
有几个问题想问一下
- 关于sign的md5值中的salt 请问是如何逆向出来的？
- v3的api中t参数是否有解决思路？

感谢~

**Comment by NothAmor** [comment]
* salt值我也是看其它大佬开源出来的算法，不太清楚是如何逆向出来的，不过跟一个大佬有过交流，用cryptoJS逆向，我自己还没有尝试过
* v3中的t参数那个大佬算出来了，我等下问问他愿不愿意开源，是AES加密，他也是说同学在源码里看到的加密源码才解出来的

目前版本的话，登陆拿token和userId用v1接口，打卡用v2接口，也是可以实现的，可以参考`app/cron/cron.py`中的CHECK函数体，这个方法避免掉了t参数，所以我没在这个程序里加进来

**Comment by NothAmor** [comment]
跟大佬沟通过了，等下他开源出来后我发给你repository链接

**Comment by SuzukiHonoka** [comment]
好的，感谢！！

**Comment by NothAmor** [comment]
https://github.com/HunterX-327/Moguding-TimeCrypto

**Comment by SuzukiHonoka** [comment]
学习了！！
